#!/usr/bin/env python3
# Multi-node system test for vertex_ros2 (design §7 acceptance).
#
# Launches THREE `vertex_node` processes (each remapped into its own /vN
# namespace), drives them through the lifecycle, and asserts the core
# guarantees:
#   * no messages on /vN/vertex/event while a node is Inactive;
#   * after activation, a transaction published on one node's /tx is delivered
#     to every node, and all three /vertex/event streams are BYTE-FOR-BYTE
#     identical (the real Vertex-order guarantee, design G4);
#   * a deactivate -> activate cycle completes without crashing.
#
# Requires ROS 2 (Jazzy baseline) + a colcon-built workspace. Run with:
#     colcon test --packages-select vertex_ros2
#   or directly:
#     launch_test src/vertex_ros2/test/system_three_peers.launch_test.py
#
# Prerequisite: test/fixtures/peers.json (generated by test/gen_test_keys.sh).

import json
import os
import time
import unittest

import launch
import launch_ros.actions
import launch_testing
import launch_testing.actions
import pytest
import rclpy
from rclpy.node import Node

from std_msgs.msg import String
from vertex_ros2_msgs.msg import VertexEvent, VertexTransaction
from vertex_ros2_msgs.srv import VertexTransition

HERE = os.path.dirname(__file__)
PEERS_PATH = os.path.join(HERE, "fixtures", "peers.json")


def _load_peers():
    if not os.path.exists(PEERS_PATH):
        pytest.skip(
            f"{PEERS_PATH} missing — run test/gen_test_keys.sh first "
            "(needs the tashi-vertex-rs key-generate example)."
        )
    with open(PEERS_PATH) as f:
        return json.load(f)


@pytest.mark.launch_test
def generate_test_description():
    peers = _load_peers()
    actions = []
    for i, me in enumerate(peers):
        others = [p for j, p in enumerate(peers) if j != i]
        peer_specs = [f"{p['public']}@{p['addr']}" for p in others]
        ns = f"/v{i}"
        actions.append(
            launch_ros.actions.Node(
                package="vertex_ros2",
                executable="vertex_node",
                name=f"vertex{i}",
                # Remap the (absolute) contract topics/services into this node's
                # namespace so three instances coexist on one machine.
                remappings=[
                    ("/vertex/tx", f"{ns}/vertex/tx"),
                    ("/vertex/event", f"{ns}/vertex/event"),
                    ("/vertex/sync_point", f"{ns}/vertex/sync_point"),
                    ("/vertex/status", f"{ns}/vertex/status"),
                    ("/vertex/transition", f"{ns}/vertex/transition"),
                    ("/vertex/lifecycle/state", f"{ns}/vertex/lifecycle/state"),
                ],
                parameters=[
                    {
                        "vertex.bind_address": me["addr"],
                        "vertex.secret_key_base58": me["secret"],
                        "vertex.peers": peer_specs,
                        "options.heartbeat_us": 50000,
                    }
                ],
                output="screen",
            )
        )
    actions.append(launch_testing.actions.ReadyToTest())
    return launch.LaunchDescription(actions), {"peers": peers}


class TestThreePeers(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        rclpy.init()
        cls.node = Node("vertex_system_test")
        cls.n = 3

    @classmethod
    def tearDownClass(cls):
        cls.node.destroy_node()
        rclpy.shutdown()

    # --- helpers ---

    def _transition(self, i, verb, timeout=10.0):
        cli = self.node.create_client(VertexTransition, f"/v{i}/vertex/transition")
        self.assertTrue(cli.wait_for_service(timeout_sec=timeout), f"v{i} transition svc")
        req = VertexTransition.Request()
        req.transition = verb
        fut = cli.call_async(req)
        rclpy.spin_until_future_complete(self.node, fut, timeout_sec=timeout)
        self.assertIsNotNone(fut.result(), f"v{i} {verb} timed out")
        return fut.result()

    def _spin(self, seconds):
        end = time.time() + seconds
        while time.time() < end:
            rclpy.spin_once(self.node, timeout_sec=0.05)

    # --- the test ---

    def test_ordered_streams_identical(self):
        # Subscribe to every node's event stream up front.
        received = {i: [] for i in range(self.n)}
        subs = []
        for i in range(self.n):
            subs.append(
                self.node.create_subscription(
                    VertexEvent,
                    f"/v{i}/vertex/event",
                    (lambda i: lambda msg: received[i].append(msg))(i),
                    10,
                )
            )

        # Configure all, then assert NOTHING is published while Inactive.
        for i in range(self.n):
            self.assertTrue(self._transition(i, "configure").success)
        self._spin(2.0)
        for i in range(self.n):
            self.assertEqual(
                len(received[i]), 0, f"v{i} published on /vertex/event while Inactive"
            )

        # Activate all.
        for i in range(self.n):
            res = self._transition(i, "activate")
            self.assertTrue(res.success, res.message)
            self.assertEqual(res.state, "active")

        # Let the session form, then publish attributable txs from every node.
        self._spin(2.0)
        pub = {
            i: self.node.create_publisher(VertexTransaction, f"/v{i}/vertex/tx", 10)
            for i in range(self.n)
        }
        needed = set()
        for i in range(self.n):
            for k in range(4):
                payload = f"node{i}-tx{k:03}".encode()
                needed.add(payload)
                msg = VertexTransaction()
                msg.payload = list(payload)
                pub[i].publish(msg)

        # Collect until every node has seen all txs (or 40s elapse).
        deadline = time.time() + 40.0
        while time.time() < deadline:
            rclpy.spin_once(self.node, timeout_sec=0.1)
            if all(
                needed.issubset(
                    {bytes(tx.payload) for ev in received[i] for tx in ev.transactions}
                )
                for i in range(self.n)
            ):
                break

        for i in range(self.n):
            delivered = {bytes(tx.payload) for ev in received[i] for tx in ev.transactions}
            self.assertTrue(needed.issubset(delivered), f"v{i} missing txs: {needed - delivered}")

        # THE guarantee: identical totally-ordered event streams across peers.
        min_len = min(len(received[i]) for i in range(self.n))
        self.assertGreater(min_len, 0)
        for idx in range(min_len):
            e0 = received[0][idx]
            for i in range(1, self.n):
                ei = received[i][idx]
                self.assertEqual(bytes(e0.hash), bytes(ei.hash), f"event #{idx} hash differs v0 vs v{i}")
                self.assertEqual(
                    [bytes(t.payload) for t in e0.transactions],
                    [bytes(t.payload) for t in ei.transactions],
                    f"event #{idx} tx order differs v0 vs v{i}",
                )

        # Lifecycle cycle on one node (depends on §9.3 Engine::stop behavior).
        self.assertTrue(self._transition(0, "deactivate").success)
        self.assertTrue(self._transition(0, "activate").success)

        for s in subs:
            self.node.destroy_subscription(s)


@launch_testing.post_shutdown_test()
class TestCleanShutdown(unittest.TestCase):
    def test_exit_codes(self, proc_info):
        # No node should have crashed.
        launch_testing.asserts.assertExitCodes(proc_info)
